[project]
name = "adversarial-attacks-on-neural-networks-a-game-theory-approach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "keras>=3.13.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "tensorflow>=2.21.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
adversarial-attacks-on-neural-networks-a-game-theory-approach = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "adversarial-attacks-on-neural-networks-a-game-theory-approach",
]
